; Title: Taylor Disk Optimizer 
; Program: Taylor Disk Optimizer Full Install
; Author: David G Horsman
; Company: dba MacroDM
; Named in memory of Matt Taylor.
; Copyright: 2015, 2019, 2020, 2021 David G Horsman
; License: Yet to be determined.
;
; Nsis Install Script: TaylorDoSetupFull
; Code Source and style: Numerous sources & online answers.
; Script generated by the HM NIS Edit Script Wizard.
; Taken from: HM NIS Edit Wizard helper defines

;--------------- Application -----------------
!define PRODUCT_NAME "Taylor Disk Optimizer"
!define PRODUCT_VERSION "3.2"
!define PRODUCT_PUBLISHER "David G Horsman"
Var /GLOBAL ProductAppName 
Var /GLOBAL ProductAppVersion 
Var /GLOBAL ProductAppPublisher 
Icon "G:\Dev\MdmDefrag\TaylorDOVs0_2\Resources\Icons\MdmControl.ico"

SetCompressor lzma
 
;--------------- Version Information -----------------
; VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "${PRODUCT_NAME}"
; VIAddVersionKey /LANG=${LANG_ENGLISH} "Comments" "An advanced automatic disk optimization library dedicated to Matt Taylor"
; VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "dba MacroDM (David G Horsman)"
; VIAddVersionKey /LANG=${LANG_ENGLISH} "InternalName" "MdmDefrag"
; VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalTrademarks" "none"
; VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "© 2015, 2020, 2021 David G Horsman"
; VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "TaylorDO Application using My Defrag Vs4.3.1"
; VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "3.0"

;--------------- Main -----------------
Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
Caption "Matt Taylor Disk Optimizer"
InstallDir "$PROGRAMFILES\MyDefrag"
; InstallDir "$PROGRAMFILES\TaylorDO"
; Get installation folder from registry if available
InstallDirRegKey HKCU "Software\${PRODUCT_NAME}" "Install_Dir"
Var /GLOBAL InstallDirTaylorDo
OutFile "TaylorDOSetup.exe"
; OutFile "TaylorDiskOptimizerSetup.exe"

RequestExecutionLevel Admin
ShowInstDetails show

;--------------- User Interface -----------------
; !include "UserManagement.nsh"
 
; MUI 1.67 compatible ------
!include "MUI.nsh"
 
; MUI Settings
!define MUI_ABORTWARNING
; !define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"
; !define MUI_ICON "${NSISDIR}\Resources\Icons\MdmControl.ico"
; G:\Dev\MdmDefrag\TaylorDOVs0_2
!define MUI_ICON "..\Resources\Icons\MdmControl.ico"

; Install 
    ; Welcome page
    !define MUI_WELCOMEPAGE_TITLE "Welcome to the Taylor Disk Optimizer ${PRODUCT_VERSION} Setup Wizard"
    !define MUI_WELCOMEPAGE_TEXT "This wizard will guide you through the installation of the TaylorDO (Taylor Disk Optimizer) ${PRODUCT_VERSION}, the next generation of the Windows disk optimization and defragmentation.$\r$\n$\r$\nTaylorDO works out of the box and tuned for the home user.$\r$\n$\r$\nBut it is designed for network system administration, is highly customizable and easy to change.$\r$\n$\r$\n$_CLICK"
    !insertmacro MUI_PAGE_WELCOME


    !insertmacro MUI_PAGE_LICENSE "..\License.txt"
    ; Components page
    !insertmacro MUI_PAGE_COMPONENTS
    ; Instfiles page
    !insertmacro MUI_PAGE_INSTFILES
    ; Finish page
    !insertmacro MUI_PAGE_FINISH

; Uninstall
    !insertmacro MUI_UNPAGE_WELCOME
    !insertmacro MUI_UNPAGE_CONFIRM
    !insertmacro MUI_UNPAGE_LICENSE "..\License.txt"
    !insertmacro MUI_UNPAGE_COMPONENTS
    !insertmacro MUI_UNPAGE_DIRECTORY
    !insertmacro MUI_UNPAGE_INSTFILES
    !insertmacro MUI_UNPAGE_FINISH
  
; Language files
!insertmacro MUI_LANGUAGE "English"
 
; Reserve files
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS
; !insertmacro MUI_RESERVEFILE_LANGDLL

; MUI end ------

; ///////////////// SECTIONS ////////////////////////////
; ///////////////// SETTINGS ////////////////////////////
Section -SETTINGS
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
    StrCpy $ProductAppName "My Defrag"
    StrCpy $ProductAppVersion "4.3.1"
    StrCpy $ProductAppPublisher "J.C. Kessels"
    StrCpy $InstallDirTaylorDo "Scripts\TaylorDO"
SectionEnd
 

; These are the programs that are needed by the Matt Taylor Disk Optimizer Suite.

; ///////////////// My Defrag ////////////////////////////
Section MyDefrag

; Check if it exists.
  IfFileExists '$INSTDIR\MyDefrag v4.3.1\MyDefrag.exe' +2 0
    Goto myDefragInstall
    Goto myDefragExists
myDefragExists:
; Display message program exists.
; Do I want an uninstall/reinstall / repair?
; Command here.
  Goto myDefragEnd
;
myDefragInstall:
  SetOutPath $INSTDIR
  SetOverwrite ifnewer
  SetShellVarContext all
  ;
; \MyDefragVs4_3_1
  MessageBox MB_YESNO "Installing MyDefrag is required. Okay?" /SD IDYES IDNO myDefragEnd
    File "..\Download\MyDefrag-v4.3.1.exe"
    ExecWait "..\Download\MyDefrag-v4.3.1.exe"
    ; /silent ?
; check for error?
    Goto myDefragEnd
myDefragEnd:

SectionEnd

; ///////////////// Matt Taylor Libraries ///////////////////////////
Section TaylorLibraries
; Initialization
; CreateDirectory $INSTDIR\backup
; CopyFiles $INSTDIR\*.log $INSTDIR\backup

; $OUTDIR 
SetOutPath $INSTDIR\Scripts\TaylorDO
;--------------- Check if it exists ----------------- IT'S THE $ SIGN #2
IfFileExists '$OUTDIR\$ Readme.txt' +2 0
    Goto taylorDefragInstall
    Goto taylorDefragExists
;
taylorDefragExists:
; Display message program exists.
; Do I want an uninstall/reinstall / repair?
; Command here.
  Goto taylorDefragEnd
;
taylorDefragInstall:
;
    SetShellVarContext all
;--------------- Copy Files -----------------
    CreateDirectory $INSTDIR\Scripts\TaylorDO
    ; File ..\*.*
    File ..\*

;--------------- CREATE SHORT CUTS -----------------
Var /GLOBAL StartMenuFolder 
StrCpy $StartMenuFolder "${PRODUCT_NAME}"

CreateDirectory "$SMPROGRAMS\$StartMenuFolder"

; TODO This is a lot of work.
CreateShortCut "$SMPROGRAMS\$StartMenuFolder\Run NSIS Example Application 1.lnk" "$SYSDIR\javaw.exe" "NSISExampleApplication1"

; Uninstall
CreateShortCut "$SMPROGRAMS\$StartMenuFolder\Uninstall Example Application 1.lnk" "$INSTDIR\Uninstall.exe"

;--------------- end of shortcuts -----------------

;--------------- Registry -----------------
  ; Get installation folder from registry if available
  ;InstallDirRegKey HKCU "Software\${PRODUCT_NAME}" "Install_Dir"

  ; Write the installation path into the registry
  WriteRegStr HKLM "Software\${PRODUCT_NAME}" "Install_Dir" "$INSTDIR"
  
  ; Write the uninstall keys for Windows
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$StartMenuFolder" "DisplayName" "$StartMenuFolder (remove only)"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$StartMenuFolder" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$StartMenuFolder" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\$StartMenuFolder" "NoRepair" 1
  WriteUninstaller "$INSTDIR\uninstall.exe"

;--------------- end of regristry keys -----------------
;
taylorDefragEnd:
;--------------- end of INSTALL Matt Taylor Libraries -----------------
SectionEnd

; ///////////////// UNISTALL ///////////////////////////

;--------------------------------
;Uninstaller Section

Section "Uninstall"

  ;ADD YOUR OWN FILES HERE...

  Delete "$INSTDIR\Uninstall.exe"

  RMDir "$INSTDIR"

  DeleteRegKey /ifempty HKCU "Software\${PRODUCT_NAME}"

SectionEnd
