cls
rem            Delete \CABLE files present on floppies...
echo.      del \cable\rosmedia.map
echo.      del \cable\ros0????.*
echo.      del \cable\roserror.*
echo.      del \cable\ros1????.*
echo.      del \cable\ros10250.020
echo.      del \cable\ros10250.030
echo.      del \cable\ros10250.040
echo.      del \cable\ros10251.*
echo.      del \cable\*.exe
echo.      del \cable\*.com
echo.      del \cable\$???????.*
echo.      del \cable\*.xtk
echo.      del \cable\*.xts
echo.      del \cable\xtalk.hlp
echo.      del \cable\xthelp.dir
echo.      del \cable\xtalk.pif
echo.
@CD
echo.
echo.  Enter <break> to abort!
PAUSE
del \cable\rosmedia.map
del \cable\ros0????.*
del \cable\roserror.*
del \cable\ros1????.*
del \cable\ros10250.020
del \cable\ros10250.030
del \cable\ros10250.040
del \cable\ros10251.*
del \cable\*.exe
del \cable\*.com
del \cable\$???????.*
del \cable\*.xtk
del \cable\*.xts
del \cable\xtalk.hlp
del \cable\xthelp.dir
del \cable\xtalk.pif
