@Rem
@Echo Off
@Rem
@Set TapCmd=Tape.Exe
@Set TapDir=\Tape\Colorado\Jumbo350\VsXXX
@Set TapObj=Tape.Exe
@Set CmdTap=
@Set DirTap=\Tape\Colorado\Jumbo350\VsXXX\Tape.Exe
@Set TapP=
@Set TapCmdTsr=AutoBack.Com
@Set TapDirTsr=\Tape\Colorado\Jumbo350\VsXXX
@Set TapObjTsr=AutoBack.Com
@Set CmdTapTsr=
@Set DirTapTsr=\Tape\Colorado\Jumbo350\VsXXX\AutoBack.Com
@Set TapPTsr=
@Rem Set TapPTsr= %OpSys.Drv%\Tape\Colorado\Jumbo350\VsXXX
