/************************************************/
/*												*/
/*	Net Library System							*/
/*	Gathering Server							*/
/*	Copyright (C) Microsoft Corp., 1997			*/
/*	All Rights Reserved							*/
/*												*/
/*	FILE_: GSrvCtr.h							*/
/*												*/
/*	Gathering Server counters object			*/
/*												*/
/************************************************/

#define OBJECT_GATHERER											0

#define COUNTER_GATHERER_NOTIFY_ADDS							2  
#define COUNTER_GATHERER_NOTIFY_ADDS_PER_SEC					4  
#define COUNTER_GATHERER_NOTIFY_DELETES							6  
#define COUNTER_GATHERER_NOTIFY_DELETES_PER_SEC					8  
#define COUNTER_GATHERER_NOTIFY_MODIFIES						10 
#define COUNTER_GATHERER_NOTIFY_MODIFIES_PER_SEC				12 
#define COUNTER_GATHERER_QUEUE_LENGTH							14 
#define COUNTER_GATHERER_IN_PROGRESS							16 
#define COUNTER_GATHERER_ON_HOLD								18 
#define COUNTER_GATHERER_DELAYED								20
#define COUNTER_GATHERER_HISTORY_SIZE							22 
#define COUNTER_GATHERER_TRANSACTIONS_PROCESSED					24 
#define COUNTER_GATHERER_TRANSACTIONS_PROCESSED_PER_SEC			26 
#define COUNTER_GATHERER_STATUS_SUCCESS							28 
#define COUNTER_GATHERER_STATUS_SUCCESS_PER_SEC					30 
#define COUNTER_GATHERER_STATUS_ERROR							32 
#define COUNTER_GATHERER_STATUS_ERROR_PER_SEC					34 
#define COUNTER_GATHERER_STATUS_FILE_ERRORS						40 
#define COUNTER_GATHERER_STATUS_FILE_ERRORS_PER_SEC				42 
#define COUNTER_GATHERER_ACCESSED_FILE							48 
#define COUNTER_GATHERER_ACCESSED_FILE_PER_SEC					50 
#define COUNTER_GATHERER_FILTERED_OFFICE						56 
#define COUNTER_GATHERER_FILTERED_OFFICE_PER_SEC				58 
#define COUNTER_GATHERER_FILTERED_TEXT							60 
#define COUNTER_GATHERER_FILTERED_TEXT_PER_SEC					62 
#define COUNTER_GATHERER_CRAWLS_IN_PROGRESS						64 
#define COUNTER_GATHERER_PAUSED									66 
#define COUNTER_GATHERER_RECOVERY_IN_PROGRESS					68
#define COUNTER_GATHERER_NOT_MODIFIED							70
#define COUNTER_GATHERER_ITERATING_HISTORY						72
#define COUNTER_GATHERER_INCREMENTAL_CRAWLS						74
#define COUNTER_GATHERER_TRANSACTIONS_BEING_FILTERED			76
#define COUNTER_GATHERER_TRANSACTIONS_STARTED					78
#define COUNTER_GATHERER_RETRIES								80
#define COUNTER_GATHERER_RETRIES_PER_SEC						82

#define COUNTER_GATHERER_AC_ERRORS								90
#define COUNTER_GATHERER_CHANGED_DOCS							96

#define COUNTER_GATHERER_NOTIFY_MOVES							98  
#define COUNTER_GATHERER_NOTIFY_MOVES_PER_SEC					100  
#define COUNTER_GATHERER_UNIQUE_DOCUMENTS						102 
#define COUNTER_GATHERER_HISTORY_RECOVERY_PROGRESS              104

