@Rem
@Echo Off
@Rem
@Echo.@
@Echo.@                  SYSTEM MANAGER -  SET PARAMETERS MENU
@Echo.@
@Echo.@
@Echo.@ Enter one of the following SET???? commands:
@Echo.@
@Echo.@    BATs         CONFIg
@Echo.@    DOS          DOSKEy       DRiVe
@Echo.@    FAX          FaSTopen
@Echo.@    LANetwork
@Echo.@    MOUse        MSDiag
@Echo.@    NATIVe
@Echo.@    OPSYS
@Echo.@    PATH         PiCK         PCTools      PORT         PROMPt
@Echo.@    QeMM
@Echo.@    REC          REV
@Echo.@    SHaRe        SMarTdrive   SerVer
@Echo.@    TAPe         TLD
@Echo.@    UNX
@Echo.@
@Echo.@ Or EXIT_CONFIG to return to the USER menu . . .
@Echo.@
