//
//    Copyright (C) Microsoft.  All rights reserved.
//
//
// usbperf.h
//

#define BULK_COUNTER 0
#define ISO_COUNTER  2
#define INTERRUPT_COUNTER 4
#define CONTROL_COUNTER 6
#define PCI_INTERRUPT_COUNTER 8
#define WORK_SIGNALS_COUNTER 10
#define INTERRUPT_BW_USAGE 12
#define ISO_BW_USAGE 14
#define USBPERF_IO 16
#define BYTES_PER_TRANSFER 18
#define DROPPED_ISO_PACKETS 20
#define AVG_ISO_LATENCY    22
#define TRANSFER_ERRORS     24
#define CONTROLLER_IDLE_STATE 26
#define CONTROLLER_ASYNC_IDLE_STATE 28
#define CONTROLLER_ASYNC_FLUSH_COUNT 30
#define CONTROLLER_PERIODIC_IDLE_STATE 32
#define CONTROLLER_PERIODIC_FLUSH_COUNT 34